# LOGGING 

[logging]
version = 1
disable_existing_loggers = false

# logs format
[logging.formatters.simple]
format = "{levelname:8} {asctime} {module}:{lineno} {message}"
style = "{"
datefmt = "%Y-%m-%d %H:%M:%S"

# write logs to console
[logging.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "simple"

# finestrino worker logging
[logging.loggers.finestrino-interface]
handlers = ["console"]
level = "DEBUG"
disabled = false
propagate = false

# finestrinod logging 
[logging.loggers.finestrino]
handlers = ["console"]
level = "DEBUG"
disabled = false
propagate = false 