rabbitmq:
  image: rabbitmq:3-management-alpine
  command: rabbitmq-plugins enable rabbitmq_mqtt
consumer: 
  build: nomads/backend/internal/consumer
  links:
  - rabbitmq 
  command: python consumer.py
producer:
  build: nomads/backend/internal/producer
  links: 
  - rabbitmq
  command: python producer.py
