###############################################################
## External monitoring using ping IPs, port scans and GeoIP 
###############################################################
title = "TOML Configuration File for Backend Monitoring Robot"

[external-monitoring]
vlabs = [ "vlab3" ]
ip-ping-freq-min = "2"
port-scan-freq-min = "2"

[internal-monitoring]
vlab-underneath = "vlab3"

[database]
server = "192.24.0.2"